site_name: Material Clean
site_url: https://indra87g.github.io
theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  features:
    - navigation.footer

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com
